world =[
      'BBBBBBBBBBBBBBBBBBBB',
      'B                  B',
      'B                  B',
      'B                  B',
      'B      BB   BB     B',
      'B    BBBBBBBBBB    B',
      'B   BB        B    B',
      'B   BB        B    B',
      'B    B        B    B',
      'B    B        B    B',
      'B    B        B    B',
      'B    B        BB   B',
      'B   BB        BB   B',
      'B   BB        B    B',
      'B    BBBBBBBBBB    B',
      'B          BB      B',
      'B                  B',
      'B                  B',
      'B                  B',
      'BBBBBBBBBBBBBBBBBBBB']